from customtkinter import *
from tkinter import *
from PIL import Image
from tkcalendar import Calendar

class CadastroWindow(CTkToplevel):
    def __init__(self, parent, controller):
        super().__init__(parent)
        self.controller = controller

        self.dark_blue = "#0057A7"
        self.blue = "#0076E3"
        self.blue_light_1 = "#A5D4FF"
        self.blue_light_2 = "#DAEDFF"
        self.blue_light_3 = "#EEF7FF"
        self.white = "#FFFFFF"
        self.gray = "#BCBCBC"
        self.gray_light = "#F0F0F0"
        self.gray_light2 = '#F5F6FA'
        self.gray_dark = "#545454"
        self.black = "#000000"
        self.red = "#F2497C"
        self.red_light = "#FFE8F1"

        self.title("Cadastro")
        self.configure(fg_color=self.gray_light2)
        self.geometry("1200x700+300+130")
        self.resizable(False, False)

        self.fr_topbar = CTkFrame(self, width=1200, height=53, fg_color=self.blue, corner_radius=0)
        self.fr_topbar.place(x=0, y=0)
        self.img_bg_topbar = CTkImage(Image.open('assets/bg_topbar.png'), size=(691, 52))
        self.lb_bg_topbar = CTkLabel(self.fr_topbar, image=self.img_bg_topbar, text='', fg_color=self.blue).place(x=515, y=0)

        self.icon_user = CTkImage(Image.open('assets/icons/user.png'), size=(32, 32))
        self.lb_icon_user = CTkLabel(self.fr_topbar, image=self.icon_user, text='', fg_color=self.blue).place(x=24, y=10)
        self.lb_nome_usuario = CTkLabel(self.fr_topbar, text='Bruno Álex', text_color=self.white, font=('Segoe UI', 12, 'bold'), height=12).place(x=64, y=10)
        self.lb_nivel_acesso = CTkLabel(self.fr_topbar, text='Admin', text_color=self.white, font=('Segoe UI', 12, 'normal'), height=12).place(x=64, y=28)

        self.tbv_cadastros = CTkTabview(self, width=1152, height=610, fg_color=self.white, bg_color=self.gray_light2, border_color=self.gray, border_width=1.5, corner_radius=8, text_color=self.white, segmented_button_fg_color=self.gray, segmented_button_selected_color=self.blue, segmented_button_selected_hover_color=self.dark_blue, segmented_button_unselected_color=self.gray_dark, anchor=W)
        self.tbv_cadastros.place(x=24, y=66)
        self.tab_cadastro_paciente = self.tbv_cadastros.add('Cadastro de Pacientes')
        self.tab_cadastro_medicos = self.tbv_cadastros.add('Cadastro de Médicos')

        self.cadastro_paciente()
        self.cadastro_medico()

    def cadastro_paciente(self):
        self.fr_dados_paciente = CTkFrame(self.tab_cadastro_paciente, width=1117, height=458, fg_color=self.blue_light_3, border_color=self.blue_light_1, border_width=1, corner_radius=6)
        self.fr_dados_paciente.place(x=10, y=10)
        self.lb_campos_geral = CTkLabel(self.fr_dados_paciente, text='GERAL', text_color=self.black, font=('Segoe UI', 14, 'bold')).place(x=16, y=18)
        self.lb_nome_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='Nome completo', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=16, y=46)
        self.ent_nome_paciente_cadastro = CTkEntry(self.fr_dados_paciente, width=381, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_nome_paciente_cadastro.place(x=16, y=72)
        self.lb_nascimento_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='Data de nascimento', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=413, y=46)
        self.ent_nascimento_paciente_cadastro = CTkEntry(self.fr_dados_paciente, width=214, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'), placeholder_text='dd/mm/aaaa')
        self.ent_nascimento_paciente_cadastro.place(x=413, y=72)
        self.icon_bt_calendario_nascimento = CTkImage(Image.open('assets/icons/calendar-search.png'), size=(20, 20))
        self.bt_calendario_nascimento = CTkButton(self.fr_dados_paciente, width=32, height=32, text='', image=self.icon_bt_calendario_nascimento, compound='left', fg_color=self.blue_light_1, bg_color=self.blue_light_3, hover_color=self.blue_light_2, corner_radius=6, command=self.pop_calendario).place(x=634, y=72)
        self.lb_cpf_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='CPF', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=687, y=46)
        self.ent_cpf_paciente_cadastro = CTkEntry(self.fr_dados_paciente, width=210, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_cpf_paciente_cadastro.place(x=687, y=72)
        self.lb_sexo_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='Sexo', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=913, y=46)
        self.cb_sexo_paciente_cadastro = CTkComboBox(self.fr_dados_paciente, width=186, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, button_color=self.blue, button_hover_color=self.dark_blue, dropdown_fg_color=self.white, dropdown_hover_color=self.blue_light_2, dropdown_text_color=self.black, dropdown_font=('Segoe UI', 14, 'normal'), text_color=self.black, font=('Segoe UI', 14, 'normal'), values=(['Masculino', 'Feminino', 'Não-binário', 'Agênero', 'Gênero fluido', 'Não declarado']))
        self.cb_sexo_paciente_cadastro.place(x=913, y=72)
        self.lb_campos_endereco = CTkLabel(self.fr_dados_paciente, text='ENDEREÇO', text_color=self.black, font=('Segoe UI', 14, 'bold'), height=12).place(x=16, y=124)
        self.lb_cep_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='CEP', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=16, y=148)
        self.ent_cep_paciente_cadastro = CTkEntry(self.fr_dados_paciente, width=200, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_cep_paciente_cadastro.place(x=16, y=176)
        self.lb_endereco_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='Endereço', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=232, y=148)
        self.ent_endereco_paciente_cadastro = CTkEntry(self.fr_dados_paciente, width=867, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_endereco_paciente_cadastro.place(x=232, y=176)
        self.lb_bairro_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='Bairro', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=16, y=212)
        self.ent_bairro_paciente_cadastro = CTkEntry(self.fr_dados_paciente, width=373, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_bairro_paciente_cadastro.place(x=16, y=238)
        self.lb_cidade_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='Cidade', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=405, y=212)
        self.ent_cidade_paciente_cadastro = CTkEntry(self.fr_dados_paciente, width=357, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_cidade_paciente_cadastro.place(x=405, y=238)
        self.lb_estado_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='Estado', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=778, y=212)
        self.ent_estado_paciente_cadastro = CTkEntry(self.fr_dados_paciente, width=320, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_estado_paciente_cadastro.place(x=778, y=238)
        self.lb_campos_endereco = CTkLabel(self.fr_dados_paciente, text='CONTATOS', text_color=self.black, font=('Segoe UI', 14, 'bold'), height=12).place(x=16, y=292)
        self.lb_email_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='E-Mail', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=16, y=316)
        self.ent_email_paciente_cadastro = CTkEntry(self.fr_dados_paciente, width=341, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_email_paciente_cadastro.place(x=16, y=342)
        self.lb_observacao_email_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='Observação', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=373, y=316)
        self.ent_observacao_email_paciente_cadastro = CTkEntry(self.fr_dados_paciente, width=726, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_observacao_email_paciente_cadastro.place(x=373, y=342)
        self.lb_celular_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='Celular/Telefone', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=16, y=380)
        self.cb_celular_paciente_cadastro = CTkComboBox(self.fr_dados_paciente, width=228, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, button_color=self.blue, button_hover_color=self.dark_blue, dropdown_fg_color=self.white, dropdown_hover_color=self.blue_light_2, dropdown_text_color=self.black, dropdown_font=('Segoe UI', 14, 'normal'), text_color=self.black, font=('Segoe UI', 14, 'normal'), values=(['Celular', 'Celular/WhatsApp', 'Telefone']))
        self.cb_celular_paciente_cadastro.place(x=16, y=406)
        self.lb_celular_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='Tipo de contato', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=262, y=380)
        self.cb_celular_paciente_cadastro = CTkComboBox(self.fr_dados_paciente, width=228, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, button_color=self.blue, button_hover_color=self.dark_blue, dropdown_fg_color=self.white, dropdown_hover_color=self.blue_light_2, dropdown_text_color=self.black, dropdown_font=('Segoe UI', 14, 'normal'), text_color=self.black, font=('Segoe UI', 14, 'normal'), values=(['Pessoal', 'Residencial', 'Comercial']))
        self.cb_celular_paciente_cadastro.place(x=262, y=406)
        self.lb_celular_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='Número', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=508, y=380)
        self.ent_celular_paciente_cadastro = CTkEntry(self.fr_dados_paciente, width=200, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'), placeholder_text='Ex. 7190000-0000')
        self.ent_celular_paciente_cadastro.place(x=508, y=406)
        self.lb_obsevacao_celular_paciente_cadastro = CTkLabel(self.fr_dados_paciente, text='Observação', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=724, y=380)
        self.ent_obsevacao_celular_paciente_cadastro = CTkEntry(self.fr_dados_paciente, width=376, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_obsevacao_celular_paciente_cadastro.place(x=724, y=406)

        self.bt_cancelar_cadastro_paciente = CTkButton(self.tab_cadastro_paciente, width=148, height=40, text='Cancelar', text_color=self.blue, font=('Segoe UI', 12, 'bold'), fg_color=self.white, hover_color=self.blue_light_2, border_color=self.blue, border_width=1.5, corner_radius=8, command=self.fechar_cadastro)
        self.bt_cancelar_cadastro_paciente.place(x=26, y=500)
        self.bt_limpar_cadastro_paciente = CTkButton(self.tab_cadastro_paciente, width=148, height=40, text='Limpar', text_color=self.blue, font=('Segoe UI', 12, 'bold'), fg_color=self.blue_light_1, hover_color=self.blue_light_2, corner_radius=8, command=self.limpar_cadastro_paciente)
        self.bt_limpar_cadastro_paciente.place(x=792, y=500)
        self.bt_salvar_cadastro_paciente = CTkButton(self.tab_cadastro_paciente, width=148, height=40, text='Cadastrar', text_color=self.white, font=('Segoe UI', 12, 'bold'), fg_color=self.blue, hover_color=self.dark_blue, corner_radius=8)
        self.bt_salvar_cadastro_paciente.place(x=962, y=500)

    def cadastro_medico(self):
        self.fr_dados_medico = CTkFrame(self.tab_cadastro_medicos, width=1117, height=458, fg_color=self.blue_light_3, border_color=self.blue_light_1, border_width=1, corner_radius=6)
        self.fr_dados_medico.place(x=10, y=10)
        self.lb_campos_geral_medico = CTkLabel(self.fr_dados_medico, text='GERAL', text_color=self.black, font=('Segoe UI', 14, 'bold')).place(x=16, y=18)
        self.lb_codigo_paciente_cadastro = CTkLabel(self.fr_dados_medico, text='Código', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=16, y=46)
        self.ent_codigo_paciente_cadastro = CTkEntry(self.fr_dados_medico, width=90, height=32, fg_color=self.gray_light, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'), state='disabled')
        self.ent_codigo_paciente_cadastro.place(x=16, y=72)
        self.lb_nome_medico_cadastro = CTkLabel(self.fr_dados_medico, text='Nome completo', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=122, y=46)
        self.ent_nome_medico_cadastro = CTkEntry(self.fr_dados_medico, width=363, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_nome_medico_cadastro.place(x=122, y=72)
        self.lb_especialidade_paciente_cadastro = CTkLabel(self.fr_dados_medico, text='CRM/CFM', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=501, y=46)
        self.cb_especialidade_paciente_cadastro = CTkComboBox(self.fr_dados_medico, width=200, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, button_color=self.blue, button_hover_color=self.dark_blue, dropdown_fg_color=self.white, dropdown_hover_color=self.blue_light_2, dropdown_text_color=self.black, dropdown_font=('Segoe UI', 14, 'normal'), text_color=self.black, font=('Segoe UI', 14, 'normal'), values=(['Clinico', 'Obstetra', 'Pediatra', 'Ortopedista', 'Dermatologista', 'Cardiologista', 'Ginecologista']))
        self.cb_especialidade_paciente_cadastro.place(x=501, y=72)
        self.lb_crm_paciente_cadastro = CTkLabel(self.fr_dados_medico, text='Especialidade', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=717, y=46)
        self.cb_crm_paciente_cadastro = CTkComboBox(self.fr_dados_medico, width=128, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, button_color=self.blue, button_hover_color=self.dark_blue, dropdown_fg_color=self.white, dropdown_hover_color=self.blue_light_2, dropdown_text_color=self.black, dropdown_font=('Segoe UI', 14, 'normal'), text_color=self.black, font=('Segoe UI', 14, 'normal'), values=(['CRM', 'CFM']))
        self.cb_crm_paciente_cadastro.place(x=717, y=72)
        self.lb_numero_crm_medico_cadastro = CTkLabel(self.fr_dados_medico, text='Número', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=861, y=46)
        self.ent_numero_crm_medico_cadastro = CTkEntry(self.fr_dados_medico, width=122, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_numero_crm_medico_cadastro.place(x=861, y=72)
        self.lb_uf_crm_paciente_cadastro = CTkLabel(self.fr_dados_medico, text='UF', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=999, y=46)
        self.cb_uf_crm_paciente_cadastro = CTkComboBox(self.fr_dados_medico, width=100, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, button_color=self.blue, button_hover_color=self.dark_blue, dropdown_fg_color=self.white, dropdown_hover_color=self.blue_light_2, dropdown_text_color=self.black, dropdown_font=('Segoe UI', 14, 'normal'), text_color=self.black, font=('Segoe UI', 14, 'normal'), values=(['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']))
        self.cb_uf_crm_paciente_cadastro.place(x=999, y=72)
        self.lb_cpf_medico_cadastro = CTkLabel(self.fr_dados_medico, text='CPF', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=16, y=110)
        self.ent_cpf_medico_cadastro = CTkEntry(self.fr_dados_medico, width=186, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_cpf_medico_cadastro.place(x=16, y=134)
        self.lb_rg_medico_cadastro = CTkLabel(self.fr_dados_medico, text='RG', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=218, y=110)
        self.ent_rg_medico_cadastro = CTkEntry(self.fr_dados_medico, width=186, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_rg_medico_cadastro.place(x=218, y=134)
        self.lb_orgao_rg_paciente_cadastro = CTkLabel(self.fr_dados_medico, text='Órgão', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=420, y=110)
        self.cb_orgao_rg_paciente_cadastro = CTkComboBox(self.fr_dados_medico, width=117, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, button_color=self.blue, button_hover_color=self.dark_blue, dropdown_fg_color=self.white, dropdown_hover_color=self.blue_light_2, dropdown_text_color=self.black, dropdown_font=('Segoe UI', 14, 'normal'), text_color=self.black, font=('Segoe UI', 14, 'normal'), values=(['SSP']))
        self.cb_orgao_rg_paciente_cadastro.place(x=420, y=134)
        self.lb_uf_rg_paciente_cadastro = CTkLabel(self.fr_dados_medico, text='UF', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=553, y=110)
        self.cb_uf_rg_paciente_cadastro = CTkComboBox(self.fr_dados_medico, width=100, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, button_color=self.blue, button_hover_color=self.dark_blue, dropdown_fg_color=self.white, dropdown_hover_color=self.blue_light_2, dropdown_text_color=self.black, dropdown_font=('Segoe UI', 14, 'normal'), text_color=self.black, font=('Segoe UI', 14, 'normal'), values=(['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']))
        self.cb_uf_rg_paciente_cadastro.place(x=553, y=134)
        self.lb_sexo_paciente_cadastro = CTkLabel(self.fr_dados_medico, text='Sexo', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=669, y=110)
        self.cb_sexo_paciente_cadastro = CTkComboBox(self.fr_dados_medico, width=162, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, button_color=self.blue, button_hover_color=self.dark_blue, dropdown_fg_color=self.white, dropdown_hover_color=self.blue_light_2, dropdown_text_color=self.black, dropdown_font=('Segoe UI', 14, 'normal'), text_color=self.black, font=('Segoe UI', 14, 'normal'), values=(['Masculino', 'Feminino', 'Não-binário', 'Agênero', 'Gênero fluido', 'Não declarado']))
        self.cb_sexo_paciente_cadastro.place(x=669, y=134)
        self.lb_nascimento_medico_cadastro = CTkLabel(self.fr_dados_medico, text='Data de nascimento', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=847, y=110)
        self.ent_nascimento_medico_cadastro = CTkEntry(self.fr_dados_medico, width=210, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'), placeholder_text='dd/mm/aaaa')
        self.ent_nascimento_medico_cadastro.place(x=847, y=134)
        self.icon_bt_calendario_nascimento_medico = CTkImage(Image.open('assets/icons/calendar-search.png'), size=(20, 20))
        self.bt_calendario_nascimento_medico = CTkButton(self.fr_dados_medico, width=32, height=32, text='', image=self.icon_bt_calendario_nascimento, compound='left', fg_color=self.blue_light_1, bg_color=self.blue_light_3, hover_color=self.blue_light_2, corner_radius=6, command=self.pop_calendario).place(x=1063, y=134)
        self.lb_campos_endereco_medico = CTkLabel(self.fr_dados_medico, text='ENDEREÇO', text_color=self.black, font=('Segoe UI', 14, 'bold'), height=12).place(x=16, y=186)
        self.lb_cep_medico_cadastro = CTkLabel(self.fr_dados_medico, text='CEP', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=16, y=208)
        self.ent_cep_medico_cadastro = CTkEntry(self.fr_dados_medico, width=141, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_cep_medico_cadastro.place(x=16, y=232)
        self.lb_endereco_medico_cadastro = CTkLabel(self.fr_dados_medico, text='Endereço', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=173, y=208)
        self.ent_endereco_medico_cadastro = CTkEntry(self.fr_dados_medico, width=352, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_endereco_medico_cadastro.place(x=173, y=232)
        self.lb_numero_medico_cadastro = CTkLabel(self.fr_dados_medico, text='Número', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=541, y=208)
        self.ent_numero_medico_cadastro = CTkEntry(self.fr_dados_medico, width=70, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_numero_medico_cadastro.place(x=541, y=232)
        self.lb_bairro_medico_cadastro = CTkLabel(self.fr_dados_medico, text='Bairro', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=627, y=208)
        self.ent_bairro_medico_cadastro = CTkEntry(self.fr_dados_medico, width=170, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_bairro_medico_cadastro.place(x=627, y=232)
        self.lb_cidade_medico_cadastro = CTkLabel(self.fr_dados_medico, text='Cidade', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=813, y=208)
        self.ent_cidade_medico_cadastro = CTkEntry(self.fr_dados_medico, width=177, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_cidade_medico_cadastro.place(x=813, y=232)
        self.lb_estado_paciente_cadastro = CTkLabel(self.fr_dados_medico, text='Estado', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=1006, y=208)
        self.cb_estado_paciente_cadastro = CTkComboBox(self.fr_dados_medico, width=95, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, button_color=self.blue, button_hover_color=self.dark_blue, dropdown_fg_color=self.white, dropdown_hover_color=self.blue_light_2, dropdown_text_color=self.black, dropdown_font=('Segoe UI', 14, 'normal'), text_color=self.black, font=('Segoe UI', 14, 'normal'), values=(['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']))
        self.cb_estado_paciente_cadastro.place(x=1006, y=232)
        self.lb_campos_contato_medico = CTkLabel(self.fr_dados_medico, text='CONTATOS', text_color=self.black, font=('Segoe UI', 14, 'bold'), height=12).place(x=16, y=292)
        self.lb_email_medico_cadastro = CTkLabel(self.fr_dados_medico, text='E-Mail', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=16, y=316)
        self.ent_email_medico_cadastro = CTkEntry(self.fr_dados_medico, width=341, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_email_medico_cadastro.place(x=16, y=342)
        self.lb_observacao_email_medico_cadastro = CTkLabel(self.fr_dados_medico, text='Observação', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=373, y=316)
        self.ent_observacao_email_medico_cadastro = CTkEntry(self.fr_dados_medico, width=726, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_observacao_email_medico_cadastro.place(x=373, y=342)
        self.lb_celular_medico_cadastro = CTkLabel(self.fr_dados_medico, text='Celular/Telefone', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=16, y=380)
        self.cb_celular_medico_cadastro = CTkComboBox(self.fr_dados_medico, width=228, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, button_color=self.blue, button_hover_color=self.dark_blue, dropdown_fg_color=self.white, dropdown_hover_color=self.blue_light_2, dropdown_text_color=self.black, dropdown_font=('Segoe UI', 14, 'normal'), text_color=self.black, font=('Segoe UI', 14, 'normal'), values=(['Celular', 'Celular/WhatsApp', 'Telefone']))
        self.cb_celular_medico_cadastro.place(x=16, y=406)
        self.lb_celular_medico_cadastro = CTkLabel(self.fr_dados_medico, text='Tipo de contato', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=262, y=380)
        self.cb_celular_medico_cadastro = CTkComboBox(self.fr_dados_medico, width=228, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, button_color=self.blue, button_hover_color=self.dark_blue, dropdown_fg_color=self.white, dropdown_hover_color=self.blue_light_2, dropdown_text_color=self.black, dropdown_font=('Segoe UI', 14, 'normal'), text_color=self.black, font=('Segoe UI', 14, 'normal'), values=(['Pessoal', 'Residencial', 'Comercial']))
        self.cb_celular_medico_cadastro.place(x=262, y=406)
        self.lb_celular_medico_cadastro = CTkLabel(self.fr_dados_medico, text='Número', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=508, y=380)
        self.ent_celular_medico_cadastro = CTkEntry(self.fr_dados_medico, width=200, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'), placeholder_text='Ex. 7190000-0000')
        self.ent_celular_medico_cadastro.place(x=508, y=406)
        self.lb_obsevacao_celular_medico_cadastro = CTkLabel(self.fr_dados_medico, text='Observação', text_color=self.black, font=('Segoe UI', 12, 'normal')).place(x=724, y=380)
        self.ent_obsevacao_celular_medico_cadastro = CTkEntry(self.fr_dados_medico, width=376, height=32, fg_color=self.white, bg_color=self.blue_light_2, corner_radius=6, border_color=self.black, border_width=1, text_color=self.black, font=('Segoe UI', 14, 'normal'))
        self.ent_obsevacao_celular_medico_cadastro.place(x=724, y=406)
        self.bt_cancelar_cadastro_medico = CTkButton(self.tab_cadastro_medicos, width=148, height=40, text='Cancelar', text_color=self.blue, font=('Segoe UI', 12, 'bold'), fg_color=self.white, hover_color=self.blue_light_2, border_color=self.blue, border_width=1.5, corner_radius=8, command=self.fechar_cadastro)
        self.bt_cancelar_cadastro_medico.place(x=26, y=500)
        self.bt_limpar_cadastro_medico = CTkButton(self.tab_cadastro_medicos, width=148, height=40, text='Limpar', text_color=self.blue, font=('Segoe UI', 12, 'bold'), fg_color=self.blue_light_1, hover_color=self.blue_light_2, corner_radius=8, command=self.limpar_cadastro_medico)
        self.bt_limpar_cadastro_medico.place(x=792, y=500)
        self.bt_salvar_cadastro_medico = CTkButton(self.tab_cadastro_medicos, width=148, height=40, text='Cadastrar', text_color=self.white, font=('Segoe UI', 12, 'bold'), fg_color=self.blue, hover_color=self.dark_blue, corner_radius=8)
        self.bt_salvar_cadastro_medico.place(x=962, y=500)

    def limpar_cadastro_paciente(self):
        self.ent_nome_paciente_cadastro.delete(0, END)
        self.ent_nascimento_paciente_cadastro.delete(0, END)
        self.ent_cpf_paciente_cadastro.delete(0, END)
        self.ent_cep_paciente_cadastro.delete(0, END)
        self.ent_endereco_paciente_cadastro.delete(0, END)
        self.ent_bairro_paciente_cadastro.delete(0, END)
        self.ent_cidade_paciente_cadastro.delete(0, END)
        self.ent_estado_paciente_cadastro.delete(0, END)
        self.ent_email_paciente_cadastro.delete(0, END)
        self.ent_observacao_email_paciente_cadastro.delete(0, END)
        self.ent_celular_paciente_cadastro.delete(0, END)
        self.ent_obsevacao_celular_paciente_cadastro.delete(0, END)

    def limpar_cadastro_medico(self):
        self.ent_nome_medico_cadastro.delete(0, END)
        self.ent_numero_crm_medico_cadastro.delete(0, END)
        self.ent_cpf_medico_cadastro.delete(0, END)
        self.ent_rg_medico_cadastro.delete(0, END)
        self.ent_nascimento_medico_cadastro.delete(0, END)
        self.ent_cep_medico_cadastro.delete(0, END)
        self.ent_endereco_medico_cadastro.delete(0, END)
        self.ent_numero_medico_cadastro.delete(0, END)
        self.ent_bairro_medico_cadastro.delete(0, END)
        self.ent_cidade_medico_cadastro.delete(0, END)
        self.ent_email_medico_cadastro.delete(0, END)
        self.ent_observacao_email_medico_cadastro.delete(0, END)
        self.ent_celular_medico_cadastro.delete(0, END)
        self.ent_obsevacao_celular_medico_cadastro.delete(0, END)

    def pop_calendario(self):
        self.pop = CTkToplevel(self, fg_color=self.white)
        self.pop.geometry('386x287+780+350')
        self.pop.title('Calendário')
        self.pop.resizable(False, False)
        self.pop.grab_set()
        self.pop.focus_force()
        self.calendario = Calendar(self.pop, selectmode='day')
        self.calendario.place(x=0, y=0, width=386, height=207)
        self.bt_confirmar = CTkButton(self.pop, text='Confirmar', text_color=self.white, font=('Segoe UI', 12, 'bold'), width=167, height=36, fg_color=self.blue, hover_color=self.dark_blue, command=self.get_data)
        self.bt_confirmar.place(x=18, y=231)
        self.bt_cancelar = CTkButton(self.pop, text='Cancelar', text_color=self.blue, font=('Segoe UI', 12, 'bold'), width=167, height=36, fg_color=self.blue_light_1, hover_color=self.blue_light_2, command=self.fecha_calendario)
        self.bt_cancelar.place(x=201, y=231)

    def get_data(self):
        self.ent_nascimento_paciente_cadastro.delete(0, END)
        data_nascimento = self.calendario.get_date()
        self.ent_nascimento_paciente_cadastro.insert(END, data_nascimento)
        self.pop.destroy()

    def fecha_calendario(self):
        self.pop.destroy()

    def fechar_cadastro(self):
        self.destroy()